export const sampleJournalEntries = [
  {
    date: '2024-01-03',
    entrySort: 1,
    documentType: 'BA',
    description: 'A1 Handy 30%',
    expenseGross: 3.73,
    account: 'Telefon',
    taxCode: '2-20',
    vatRate: 20,
    inputVat: 0.62,
  },
  {
    date: '2024-01-03',
    entrySort: 2,
    documentType: 'KA',
    description: 'A1 Internet 60%',
    expenseGross: 11.99,
    account: 'Telefon',
    taxCode: '2-20',
    vatRate: 20,
    inputVat: 2.0,
  },
  {
    date: '2024-01-04',
    entrySort: 3,
    documentType: 'BA',
    description: 'Microsoft',
    expenseGross: 15.6,
    account: 'Software',
    taxCode: '19-20',
    vatRate: 20,
    inputVat: 0,
  },
  {
    date: '2024-01-05',
    entrySort: 4,
    documentType: 'KA',
    description: 'OpenAI ChatGPT',
    expenseGross: 18.31,
    account: 'Software',
    taxCode: '19-20',
    vatRate: 20,
    inputVat: 0,
  },
  {
    date: '2024-01-08',
    entrySort: 5,
    documentType: 'BA',
    description: 'T-Mobile Austria GmbH',
    expenseGross: 25.0,
    account: 'Telefon',
    taxCode: '2-20',
    vatRate: 20,
    inputVat: 4.17,
  },
  {
    date: '2024-01-10',
    entrySort: 6,
    documentType: 'KA',
    description: 'BA-Computer Handel',
    expenseGross: 193.73,
    account: 'Geringwertige WG',
    taxCode: '2-20',
    vatRate: 20,
    inputVat: 32.29,
  },
  {
    date: '2024-01-10',
    entrySort: 7,
    documentType: 'BA',
    description: 'BA-Computer Handel',
    expenseGross: 691.32,
    account: 'Geringwertige WG',
    taxCode: '2-20',
    vatRate: 20,
    inputVat: 115.22,
  },
  {
    date: '2024-01-11',
    entrySort: 8,
    documentType: 'KA',
    description: 'Libro',
    expenseGross: 20.37,
    account: 'Betriebsm. Reinigung',
    taxCode: '2-20',
    vatRate: 20,
    inputVat: 3.4,
  },
  {
    date: '2024-01-29',
    entrySort: 9,
    documentType: 'BA',
    description: 'ELBEIT Consult GmbH',
    incomeGross: 7324.45,
    account: 'Erlöse sonstige Leistungen',
    taxCode: '77-0',
    vatRate: 0,
    inputVat: 0,
  },
  {
    date: '2024-01-29',
    entrySort: 10,
    documentType: 'KA',
    description: 'Feistritzthaler E-Werk',
    incomeGross: 230.35,
    account: 'Sonstige Erträge',
    taxCode: '6-0',
    vatRate: 0,
    inputVat: 0,
  },
  {
    date: '2024-02-01',
    entrySort: 1,
    documentType: 'BA',
    description: 'A1 Handy 40%',
    expenseGross: 3.99,
    account: 'Telefon',
    taxCode: '2-20',
    vatRate: 20,
    inputVat: 0.67,
  },
  {
    date: '2024-02-01',
    entrySort: 2,
    documentType: 'KA',
    description: 'A1 Internet 60%',
    expenseGross: 11.99,
    account: 'Telefon',
    taxCode: '2-20',
    vatRate: 20,
    inputVat: 2.0,
  },
  {
    date: '2024-02-01',
    entrySort: 3,
    documentType: 'BA',
    description: 'API Österreich',
    expenseGross: 28.76,
    account: 'Geringwertige WG',
    taxCode: '2-20',
    vatRate: 20,
    inputVat: 4.79,
  },
  {
    date: '2024-02-04',
    entrySort: 4,
    documentType: 'KA',
    description: 'OeMAG Oekostrom AG',
    incomeGross: 1795.0,
    account: 'Sonstige Erträge',
    taxCode: '6-0',
    vatRate: 0,
    inputVat: 0,
  },
  {
    date: '2024-02-07',
    entrySort: 5,
    documentType: 'BA',
    description: 'OeMAG Oekostrom AG',
    incomeGross: 2000.0,
    account: 'Sonstige Erträge',
    taxCode: '6-0',
    vatRate: 0,
    inputVat: 0,
  },
  {
    date: '2024-02-08',
    entrySort: 6,
    documentType: 'KA',
    description: 'Ledenika Software',
    expenseGross: 1200.0,
    account: 'Software',
    taxCode: '19-20',
    vatRate: 20,
    inputVat: 0,
  },
  {
    date: '2024-02-09',
    entrySort: 7,
    documentType: 'BA',
    description: 'ÖGK Steiermark',
    expenseGross: 1.25,
    account: 'Sozialversicherung',
    taxCode: '0-0',
    vatRate: 0,
    inputVat: 0,
  },
  {
    date: '2024-02-09',
    entrySort: 8,
    documentType: 'KA',
    description: 'OpenAI ChatGPT',
    expenseGross: 18.65,
    account: 'Software',
    taxCode: '19-20',
    vatRate: 20,
    inputVat: 0,
  },
  {
    date: '2024-02-10',
    entrySort: 9,
    documentType: 'BA',
    description: 'Finanzamt Österreich',
    expenseGross: 29.86,
    account: 'USt-Zahlungen/Rückzahlungen',
    taxCode: '0-0',
    vatRate: 0,
    inputVat: 0,
  },
  {
    date: '2024-02-15',
    entrySort: 10,
    documentType: 'KA',
    description: 'Finanzamt Österreich – ESt. 1/3 24',
    expenseGross: 4500.0,
    account: 'USt-Zahlungen/Rückzahlungen',
    taxCode: '0-0',
    vatRate: 0,
    inputVat: 0,
  },
];
